# Generated by Django 4.0.5 on 2022-06-17 16:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HRD_table',
            fields=[
                ('EID', models.CharField(max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('Name', models.CharField(max_length=30, unique=True)),
                ('DOJ', models.DateField()),
                ('Designation', models.CharField(max_length=10)),
                ('Department', models.CharField(max_length=10)),
                ('Uan', models.IntegerField(unique=True)),
                ('PF_accno', models.CharField(max_length=15, unique=True)),
                ('ESIC', models.IntegerField(unique=True)),
                ('Company_email', models.EmailField(max_length=254, unique=True)),
                ('working_hrs', models.FloatField()),
                ('appraisal_due', models.DateField()),
                ('salary', models.IntegerField()),
                ('manager', models.CharField(max_length=20)),
                ('working_days', models.IntegerField()),
            ],
            options={
                'db_table': 'HR_table',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.CharField(max_length=30)),
                ('Allocated', models.TimeField()),
                ('ActualTime', models.TimeField()),
                ('dates', models.DateField(null=True)),
            ],
            options={
                'db_table': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('Project', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('Task_in_time', models.TimeField()),
                ('Task_out_time', models.TimeField()),
                ('approval', models.BooleanField(blank=True, default=False)),
                ('EID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indvaltech.hrd_table')),
            ],
            options={
                'db_table': 'TimeSheet',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField()),
                ('Pname', models.CharField(max_length=50)),
                ('customername', models.CharField(default='none', max_length=50)),
                ('Department', models.CharField(default='none', max_length=50)),
                ('StartDate', models.DateField(max_length=50)),
                ('EndDate', models.DateField(max_length=50)),
                ('location', models.CharField(default='none', max_length=50)),
                ('ProjectDesc', models.CharField(default='none', max_length=100)),
                ('EID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indvaltech.hrd_table')),
            ],
            options={
                'db_table': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=30)),
                ('work', models.CharField(max_length=100)),
                ('tools', models.CharField(max_length=50)),
                ('last_salary', models.CharField(max_length=20)),
                ('reason_of_leaving', models.CharField(max_length=100)),
                ('EID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indvaltech.hrd_table')),
            ],
            options={
                'db_table': 'History',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('relation', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=12)),
                ('remarks', models.CharField(default=' ', max_length=100)),
                ('EID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indvaltech.hrd_table')),
            ],
            options={
                'db_table': 'Family',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.IntegerField()),
                ('aadharDoc', models.FileField(upload_to='media/')),
                ('Pan', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('panDoc', models.FileField(upload_to='media/')),
                ('passport', models.IntegerField()),
                ('passportDoc', models.FileField(upload_to='media/')),
                ('esicNum', models.IntegerField()),
                ('esicDoc', models.ImageField(upload_to='media/')),
                ('Address', models.CharField(max_length=100)),
                ('PermanentAddress', models.CharField(max_length=100)),
                ('Ph', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('Email', models.CharField(max_length=30)),
                ('Blood', models.CharField(max_length=10)),
                ('EmergencyPh', models.IntegerField()),
                ('Photo', models.ImageField(upload_to='media/')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indvaltech.hrd_table')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=30)),
                ('board', models.CharField(max_length=15)),
                ('percentage', models.IntegerField()),
                ('passing', models.IntegerField()),
                ('EID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indvaltech.hrd_table')),
            ],
            options={
                'db_table': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.FileField(upload_to='media/')),
                ('pan', models.FileField(upload_to='media/')),
                ('aadhar', models.FileField(upload_to='media/')),
                ('passport', models.FileField(upload_to='media/')),
                ('noc', models.FileField(upload_to='media/')),
                ('payslip', models.FileField(upload_to='media/')),
                ('esic', models.FileField(upload_to='media/')),
                ('experience', models.FileField(upload_to='media/')),
                ('it_form', models.FileField(upload_to='media/')),
                ('EID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indvaltech.hrd_table')),
            ],
            options={
                'db_table': 'Document',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=30)),
                ('institution_name', models.CharField(max_length=30)),
                ('board_name', models.CharField(max_length=30)),
                ('Class', models.CharField(max_length=30)),
                ('marks', models.PositiveIntegerField()),
                ('EID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indvaltech.hrd_table')),
            ],
            options={
                'db_table': 'Certification',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('account', models.IntegerField()),
                ('bank_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('ifsc', models.IntegerField(validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('swift', models.CharField(max_length=30)),
                ('iban', models.CharField(max_length=30)),
                ('EID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indvaltech.hrd_table')),
            ],
            options={
                'db_table': 'Bank',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('date', models.DateField()),
                ('EID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indvaltech.hrd_table')),
            ],
            options={
                'db_table': 'Attendance',
            },
        ),
    ]
