# Generated by Django 4.0.5 on 2022-06-22 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indvaltech', '0002_alter_employee_esicdoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='testtable',
            fields=[
                ('d1', models.IntegerField(primary_key=True, serialize=False)),
                ('d2', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='Email',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='esicDoc',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
